name: Check frontend

on:
  push:
    paths-ignore:
      - '**.lock'
      - '**.rs'
      - '**.toml'
  pull_request:
    paths-ignore:
      - '**.lock'
      - '**.rs'
      - '**.toml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0

jobs:
  tsc-eslint-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.1

      - name: Install modules
        run: bun install

      - name: Run esbuild
        run: bun build:js

      - name: Run Biome checks
        run: bun biome check --apply ./src
